
import { Product, Category, District } from './types';

export const LANGUAGES = [
  { code: 'ru', label: 'Русский', icon: '🇷🇺' },
  { code: 'kk', label: 'Қазақша', icon: '🇰🇿' },
  { code: 'en', label: 'English', icon: '🇺🇸' },
  { code: 'ky', label: 'Кыргызча', icon: '🇰🇬' }
];

export const SHYMKENT_DISTRICTS: District[] = [
  { name: 'Аль-Фарабийский район', price: 600, estimatedTime: '30-45 мин' },
  { name: 'Абайский район', price: 800, estimatedTime: '45-60 мин' },
  { name: 'Енбекшинский район', price: 700, estimatedTime: '40-55 мин' },
  { name: 'Каратауский район', price: 900, estimatedTime: '50-70 мин' }
];

export const TRANSLATIONS: any = {
  ru: {
    home: "Главная",
    catalog: "Каталог",
    wishlist: "Избранное",
    cart: "Корзина",
    trackOrder: "Отследить заказ",
    orderIdPlaceholder: "Номер заказа (напр. ORD-123)",
    trackBtn: "Где моё платье?",
    bestSellers: "Хиты продаж",
    yandexPromoTitle: "Срочная доставка?",
    yandexPromoDesc: "Привезем через Яндекс Go по Шымкенту в течение часа!",
    stayConnected: "Мы в соцсетях",
    visitUs: "Наш бутик",
    mapsHint: "Рынок Автонур, г. Шымкент",
    checkout: "Оформление заказа",
    total: "Итого",
    completeOrder: "Отправить в WhatsApp",
    deliveryMethod: "Способ получения",
    yandexDelivery: "Яндекс Go (Такси)",
    selfPickup: "Самовывоз из Автонура",
    standardDelivery: "Стандартная доставка",
    districtLabel: "Район доставки",
    shippingPrice: "Цена доставки:",
    estTime: "Примерное время:",
    status_pending: "Принят",
    status_preparing: "Собираем в Автонуре",
    status_shipped: "В пути (Яндекс Go)",
    status_delivered: "Доставлено",
    adminOrders: "Заказы",
    fullName: "Ваше имя",
    email: "Электронная почта",
    phone: "Ваш телефон",
    deliveryAddress: "Улица, дом, квартира",
    paymentKaspi: "Kaspi перевод / QR",
    backToCart: "Вернуться",
    added: "Добавлено!",
    addToCart: "В корзину",
    aiStudio: "ИИ Студия",
    aiStudioTitle: "Творческая студия",
    visualSearch: "Поиск по фото",
    aiLifestyle: "Примерить ИИ",
    compareTitle: "Сравнение моделей",
    reviews: "Отзывы",
    noReviews: "Отзывов пока нет",
    leaveReview: "Оставить отзыв",
    yourRating: "Оценка",
    yourComment: "Ваш комментарий",
    sendReview: "Отправить",
    moodFormal: "Вечерний выход",
    moodCasual: "Прогулка",
    moodCity: "Городской стиль",
    aiGenerating: "ИИ создает образ...",
    categories: "Категории",
    aiGreeting: "Здравствуйте! Я ваш ИИ-стилист в Zhumagul. Чем могу помочь?",
    aiAssistant: "ИИ Стилист",
    siteSettings: "Настройки",
    price: "Цена",
    sizes: "Размеры",
    colors: "Цвета",
    description: "Описание",
    receiptSent: "Чек об оплате отправлен на вашу почту!"
  },
  kk: {
    home: "Басты бет",
    catalog: "Каталог",
    wishlist: "Таңдаулы",
    cart: "Себет",
    trackOrder: "Тапсырысты тексеру",
    orderIdPlaceholder: "Тапсырыс нөмірі (мыс. ORD-123)",
    trackBtn: "Көйлегім қайда?",
    bestSellers: "Хит тауарлар",
    yandexPromoTitle: "Шұғыл жеткізу?",
    yandexPromoDesc: "Шымкент бойынша Яндекс Go арқылы бір сағатта жеткіземіз!",
    stayConnected: "Әлеуметтік желілер",
    visitUs: "Біздің бутик",
    mapsHint: "Шымкент қ., Автонур базары",
    checkout: "Тапсырысты рәсімдеу",
    total: "Жиыны",
    completeOrder: "WhatsApp-қа жіберу",
    deliveryMethod: "Жеткізу түрі",
    yandexDelivery: "Яндекс Go (Такси)",
    selfPickup: "Автонурдан алып кету",
    standardDelivery: "Стандартты жеткізу",
    districtLabel: "Жеткізу ауданы",
    shippingPrice: "Жеткізу құны:",
    estTime: "Болжамды уақыт:",
    status_pending: "Қабылданды",
    status_preparing: "Автонурда жиналуда",
    status_shipped: "Жолда (Яндекс Go)",
    status_delivered: "Жеткізілді",
    adminOrders: "Тапсырыстар",
    fullName: "Атыңыз",
    email: "Электронды пошта",
    phone: "Телефоныңыз",
    deliveryAddress: "Көше, үй, пәтер",
    paymentKaspi: "Kaspi аударым / QR",
    backToCart: "Қайту",
    added: "Қосылды!",
    addToCart: "Себетке салу",
    aiStudio: "AI Студия",
    aiStudioTitle: "Шығармашылық студия",
    visualSearch: "Фотомен іздеу",
    aiLifestyle: "Киіп көру",
    compareTitle: "Салыстыру",
    reviews: "Пікірлер",
    noReviews: "Пікірлер жоқ",
    leaveReview: "Пікір қалдыру",
    yourRating: "Бағалау",
    yourComment: "Пікіріңіз",
    sendReview: "Жіберу",
    moodFormal: "Кешкі жиын",
    moodCasual: "Серуендеу",
    moodCity: "Қала стилі",
    aiGenerating: "AI сурет жасауда...",
    categories: "Санаттар",
    aiGreeting: "Сәлеметсіз бе! Мен Zhumagul бутигінің AI-стилисімін. Қалай көмектесе аламын?",
    aiAssistant: "AI Стилист",
    siteSettings: "Баптаулар",
    price: "Бағасы",
    sizes: "Өлшемдері",
    colors: "Түстері",
    description: "Сипаттамасы",
    receiptSent: "Төлем чегі поштаңызға жіберілді!"
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    wishlist: "Wishlist",
    cart: "Cart",
    trackOrder: "Track Order",
    orderIdPlaceholder: "Order ID (e.g. ORD-123)",
    trackBtn: "Where's my dress?",
    bestSellers: "Best Sellers",
    yandexPromoTitle: "Express Delivery?",
    yandexPromoDesc: "Delivery via Yandex Go in Shymkent within an hour!",
    stayConnected: "Social Media",
    visitUs: "Our Boutique",
    mapsHint: "Avtonur Market, Shymkent",
    checkout: "Checkout",
    total: "Total",
    completeOrder: "Send via WhatsApp",
    deliveryMethod: "Delivery Method",
    yandexDelivery: "Yandex Go (Taxi)",
    selfPickup: "Pickup from Avtonur",
    standardDelivery: "Standard Delivery",
    districtLabel: "Delivery District",
    shippingPrice: "Shipping Price:",
    estTime: "Estimated Time:",
    status_pending: "Pending",
    status_preparing: "Preparing in Avtonur",
    status_shipped: "In Transit (Yandex Go)",
    status_delivered: "Delivered",
    adminOrders: "Orders",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    deliveryAddress: "Street, House, Apt",
    paymentKaspi: "Kaspi Transfer / QR",
    backToCart: "Back",
    added: "Added!",
    addToCart: "Add to Cart",
    aiStudio: "AI Studio",
    aiStudioTitle: "Creative Studio",
    visualSearch: "Photo Search",
    aiLifestyle: "Try on with AI",
    compareTitle: "Comparison",
    reviews: "Reviews",
    noReviews: "No reviews yet",
    leaveReview: "Leave a Review",
    yourRating: "Rating",
    yourComment: "Comment",
    sendReview: "Send",
    moodFormal: "Evening Out",
    moodCasual: "Casual Walk",
    moodCity: "City Style",
    aiGenerating: "AI is creating your look...",
    categories: "Categories",
    aiGreeting: "Hello! I am your AI stylist at Zhumagul. How can I help you?",
    aiAssistant: "AI Stylist",
    siteSettings: "Settings",
    price: "Price",
    sizes: "Sizes",
    colors: "Colors",
    description: "Description",
    receiptSent: "Payment receipt sent to your email!"
  },
  ky: {
    home: "Башкы бет",
    catalog: "Каталог",
    wishlist: "Тандалгандар",
    cart: "Себет",
    trackOrder: "Тапшырыкты текшерүү",
    orderIdPlaceholder: "Тапшырык номери (мис. ORD-123)",
    trackBtn: "Көйнөгүм кайда?",
    bestSellers: "Хит товарлар",
    yandexPromoTitle: "Тез жеткирүү?",
    yandexPromoDesc: "Шымкент боюнча Яндекс Go аркылуу бир саатта жеткиребиз!",
    stayConnected: "Биз соцтармактарда",
    visitUs: "Биздин бутик",
    mapsHint: "Автонур базары, Шымкент ш.",
    checkout: "Тапшырыкты кабыл алуу",
    total: "Жыйынтыгы",
    completeOrder: "WhatsApp аркылуу жөнөтүү",
    deliveryMethod: "Жеткирүү түрү",
    yandexDelivery: "Яндекс Go (Такси)",
    selfPickup: "Автонурдан алып кетүү",
    standardDelivery: "Стандарттык жеткирүү",
    districtLabel: "Жеткирүү аймагы",
    shippingPrice: "Жеткирүү баасы:",
    estTime: "Болжолдуу убакыт:",
    status_pending: "Кабыл алынды",
    status_preparing: "Автонурда даярдалууда",
    status_shipped: "Жолдо (Яндекс Go)",
    status_delivered: "Жеткирилди",
    adminOrders: "Тапшырыктар",
    fullName: "Атыңыз",
    email: "Электрондук почта",
    phone: "Телефонуңуз",
    deliveryAddress: "Көчө, үй, батир",
    paymentKaspi: "Kaspi которуу / QR",
    backToCart: "Кайтуу",
    added: "Кошулду!",
    addToCart: "Себетке салуу",
    aiStudio: "AI Студия",
    aiStudioTitle: "Чыгармачыл студия",
    visualSearch: "Сүрөт менен издөө",
    aiLifestyle: "Кийип көрүү",
    compareTitle: "Салыштыруу",
    reviews: "Пикирлер",
    noReviews: "Пикирлер жок",
    leaveReview: "Пикир калтыруу",
    yourRating: "Баалоо",
    yourComment: "Пикириңиз",
    sendReview: "Жөнөтүү",
    moodFormal: "Кечки кече",
    moodCasual: "Сейилдөө",
    moodCity: "Шаардык стиль",
    aiGenerating: "AI сүрөт жаратууда...",
    categories: "Категориялар",
    aiGreeting: "Саламатсызбы! Мен Zhumagul бутигинин AI-стилистимин. Кантип жардам бере алам?",
    aiAssistant: "AI Стилист",
    siteSettings: "Жөндөөлөр",
    price: "Баасы",
    sizes: "Өлчөмдөрү",
    colors: "Түстөрү",
    description: "Сүрөттөмөсү",
    receiptSent: "Төлөм чеги почтаңызга жөнөтүлдү!"
  }
};

export const MOCK_PRODUCTS: Product[] = [
  // Коллекция ИНДИЯ
  {
    id: 'in-1',
    name: 'Индийское Сари "Royal Silk"',
    price: 45000,
    category: Category.INDIA,
    description: 'Традиционное индийское платье из натурального шелка. Богатая вышивка золотыми нитями. Идеально для торжественных мероприятий.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=800',
    sizes: ['M', 'L', 'XL'],
    colors: ['Red-Gold', 'Emerald']
  },
  {
    id: 'in-2',
    name: 'Платье-Курта "Cotton Breeze"',
    price: 18500,
    category: Category.INDIA,
    description: 'Легкое летнее платье из индийского хлопка. Дышащая ткань, яркий этнический принт. Комфорт в шымкентскую жару.',
    image: 'https://images.unsplash.com/photo-1617175548993-8d0034a7428c?q=80&w=800',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Orange', 'Yellow', 'Blue']
  },
  {
    id: 'in-3',
    name: 'Вечерний комплект "Anarkali"',
    price: 32000,
    category: Category.INDIA,
    description: 'Многослойное платье в стиле Анаркали. Элегантный силуэт, подчеркивающий талию.',
    image: 'https://images.unsplash.com/photo-1542452255191-c85a99f3c5f4?q=80&w=800',
    sizes: ['S', 'M', 'L'],
    colors: ['Maroon', 'Navy']
  },

  // Коллекция КИТАЙ (Одежда)
  {
    id: 'cn-1',
    name: 'Шелковое платье "Modern Qipao"',
    price: 28000,
    category: Category.CHINA,
    description: 'Современная интерпретация традиционного китайского платья Ципао. Качественный атлас, приталенный крой.',
    image: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?q=80&w=800',
    sizes: ['XS', 'S', 'M'],
    colors: ['Black', 'Deep Red']
  },
  {
    id: 'cn-2',
    name: 'Летнее платье "Guangzhou Fashion"',
    price: 15500,
    category: Category.CHINA,
    description: 'Трендовое платье из легкой смесовой ткани. Прямые поставки из модных хабов Гуанчжоу.',
    image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?q=80&w=800',
    sizes: ['S', 'M', 'L'],
    colors: ['Lavender', 'Mint']
  },
  {
    id: 'cn-3',
    name: 'Офисное платье "Silk Touch"',
    price: 24000,
    category: Category.CHINA,
    description: 'Элегантное платье для офиса с эффектом шелка. Не мнется, отлично держит форму.',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800',
    sizes: ['M', 'L', 'XL'],
    colors: ['Beige', 'Grey']
  },

  // Коллекция КЫРГЫЗСТАН
  {
    id: 'kg-1',
    name: 'Трикотажное платье "Bishkek Soft"',
    price: 16000,
    category: Category.KYRGYZSTAN,
    description: 'Мягкий кыргызстанский трикотаж высшего качества. Удобное платье на каждый день, которое прослужит долго.',
    image: 'https://images.unsplash.com/photo-1572804013307-f97119af50c7?q=80&w=800',
    sizes: ['M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Powder Pink', 'Grey', 'Graphite']
  },
  {
    id: 'kg-2',
    name: 'Деловой костюм "Dordoi Elite"',
    price: 26500,
    category: Category.KYRGYZSTAN,
    description: 'Стильное платье-футляр с жакетом. Идеально для бизнес-встреч и работы. Качественный пошив.',
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680fe0a?q=80&w=800',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Dark Blue', 'Classic Black']
  },
  {
    id: 'kg-3',
    name: 'Праздничное платье "Osh Velvet"',
    price: 29000,
    category: Category.KYRGYZSTAN,
    description: 'Роскошное вельветовое платье с кружевными вставками. Теплая и статусная модель.',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800',
    sizes: ['L', 'XL', '2XL'],
    colors: ['Wine', 'Forest Green']
  },

  // Базовые модели (Вечерние / Повседневные)
  {
    id: 'v-1',
    name: 'Вечернее Платье "Шымкентская Ночь"',
    price: 35000,
    category: Category.EVENING,
    description: 'Элегантное черное платье с разрезом. Идеально для свадеб в ресторанах Алтын Сарай или Кайнар.',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800',
    sizes: ['S', 'M', 'L'],
    colors: ['Black'],
    reviews: [{ id: 'r1', userName: 'Айгерим', rating: 5, text: 'Очень красивое платье, село идеально!', date: '12.05.2024' }]
  },
  {
    id: 'v-2',
    name: 'Коктейльное Платье "Rose"',
    price: 28000,
    category: Category.COCKTAIL,
    description: 'Нежное платье для праздников и дней рождения.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800',
    sizes: ['XS', 'S', 'M'],
    colors: ['Pink', 'Cream']
  }
];

export const SHOP_ADDRESS = "г. Шымкент, Рынок 'Автонур', Ряд 5, Бутик 12";
export const SHOP_EMAIL = "zhumagul.boutique@gmail.com";
export const WHATSAPP_NUMBER = "77000000000";
export const INSTAGRAM_HANDLE = "zhumagul_boutique";
export const DEFAULT_HERO_IMAGE = "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=2500";
